In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, SelectPercentile, chi2
from sklearn.preprocessing import StandardScaler

In [3]:
# Loading Data
df = pd.read_csv("Data/data2.csv")

In [4]:
# Viewing dataframe
df

,DISAPPROVALS_BL,DISAPPROVALS_EN,DISAPPROVALS_FM,DISAPPROVALS_OM,NOTE_BL,NOTE_EN,NOTE_FM,NOTE_OM,ENGLISH,H_CLASS_PRES,ONLINE_TASKS,ABSENCES,NOTE_BL_CAT,NOTE_EN_CAT,NOTE_FM_CAT,NOTE_OM_CAT,PROFILE_N
0,0.0,0.0,0.0,0.0,6.2,5.8,4.6,5.9,0.0,2.0,4.0,3.0,"(6, 8]","(4, 6]","(4, 6]","(4, 6]",2.0
1,0.0,0.0,0.0,0.0,6.0,6.2,5.2,4.5,1.0,2.0,4.0,3.0,"(4, 6]","(6, 8]","(4, 6]","(4, 6]",2.0
2,0.0,0.0,0.0,0.0,7.3,6.7,7.1,7.2,0.0,5.0,0.0,3.0,"(6, 8]","(6, 8]","(6, 8]","(6, 8]",3.0
3,1.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,4.0,"(-1, 2]","(-1, 2]","(-1, 2]","(-1, 2]",1.0
4,1.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,5.0,2.0,5.0,"(-1, 2]","(-1, 2]","(-1, 2]","(-1, 2]",1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18540,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,20.0,4.0,4.0,"(-1, 2]","(-1, 2]","(-1, 2]","(-1, 2]",1.0
18541,0.0,0.0,0.0,0.0,7.0,7.9,5.8,7.0,1.0,9.0,5.0,6.0,"(6, 8]","(6, 8]","(4, 6]","(6, 8]",2.0
18542,0.0,0.0,0.0,0.0,7.9,7.6,8.3,7.2,1.0,8.0,3.0,1.0,"(6, 8]","(6, 8]","(8, 10]","(6, 8]",5.0
18543,0.0,0.0,1.0,1.0,6.3,5.1,0.0,0.0,1.0,3.0,2.0,6.0,"(6, 8]","(4, 6]","(-1, 2]","(-1, 2]",1.0
18544,0.0,0.0,1.0,1.0,7.0,7.3,0.0,0.0,1.0,3.0,0.0,6.0,"(6, 8]","(6, 8]","(-1, 2]","(-1, 2]",1.0

Generating new variables

In [5]:
# compares variables and generates a new one
def compare_human(x):
    if x["DISAPPROVALS_BL"] == 0 and x["DISAPPROVALS_EN"] == 0:
        return(0)
    else:
        return(1)
df["DISAPPROVALS_HUMAN"] = df.apply(compare_human, axis= 1)

In [6]:
def compare_exacts(x):
    if x["DISAPPROVALS_FM"] == 0 and x["DISAPPROVALS_OM"] == 0:
        return(0)
    else:
        return(1)
df["DISAPPROVALS_EXACTS"] = df.apply(compare_exacts, axis= 1)

In [7]:
# Viewing new data frame
df

,DISAPPROVALS_BL,DISAPPROVALS_EN,DISAPPROVALS_FM,DISAPPROVALS_OM,NOTE_BL,NOTE_EN,NOTE_FM,NOTE_OM,ENGLISH,H_CLASS_PRES,ONLINE_TASKS,ABSENCES,NOTE_BL_CAT,NOTE_EN_CAT,NOTE_FM_CAT,NOTE_OM_CAT,PROFILE_N,DISAPPROVALS_HUMAN,DISAPPROVALS_EXACTS
0,0.0,0.0,0.0,0.0,6.2,5.8,4.6,5.9,0.0,2.0,4.0,3.0,"(6, 8]","(4, 6]","(4, 6]","(4, 6]",2.0,0,0
1,0.0,0.0,0.0,0.0,6.0,6.2,5.2,4.5,1.0,2.0,4.0,3.0,"(4, 6]","(6, 8]","(4, 6]","(4, 6]",2.0,0,0
2,0.0,0.0,0.0,0.0,7.3,6.7,7.1,7.2,0.0,5.0,0.0,3.0,"(6, 8]","(6, 8]","(6, 8]","(6, 8]",3.0,0,0
3,1.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,4.0,"(-1, 2]","(-1, 2]","(-1, 2]","(-1, 2]",1.0,1,1
4,1.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,5.0,2.0,5.0,"(-1, 2]","(-1, 2]","(-1, 2]","(-1, 2]",1.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18540,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,20.0,4.0,4.0,"(-1, 2]","(-1, 2]","(-1, 2]","(-1, 2]",1.0,1,1
18541,0.0,0.0,0.0,0.0,7.0,7.9,5.8,7.0,1.0,9.0,5.0,6.0,"(6, 8]","(6, 8]","(4, 6]","(6, 8]",2.0,0,0
18542,0.0,0.0,0.0,0.0,7.9,7.6,8.3,7.2,1.0,8.0,3.0,1.0,"(6, 8]","(6, 8]","(8, 10]","(6, 8]",5.0,0,0
18543,0.0,0.0,1.0,1.0,6.3,5.1,0.0,0.0,1.0,3.0,2.0,6.0,"(6, 8]","(4, 6]","(-1, 2]","(-1, 2]",1.0,0,1
18544,0.0,0.0,1.0,1.0,7.0,7.3,0.0,0.0,1.0,3.0,0.0,6.0,"(6, 8]","(6, 8]","(-1, 2]","(-1, 2]",1.0,0,1

In [8]:
# Converting categorical variable into numeric variable
var = ['NOTE_BL_CAT', 'NOTE_EN_CAT', 'NOTE_FM_CAT', 'NOTE_OM_CAT']
count = 0
for i in var:
    df[count]= df[i].map({"(-1, 2]": 2,
                           "(2, 4]": 4, 
                           "(4, 6]": 6,
                           "(6, 8]": 8,
                           "(8, 10]": 10})
    count += 1
df.rename(columns={0:'NOTE_BL_CAT_N', 1:'NOTE_EN_CAT_N', 2:'NOTE_FM_CAT_N', 3:'NOTE_OM_CAT_N'}, inplace=True)

In [9]:
# checking data type 
df.dtypes

DISAPPROVALS_BL        float64
DISAPPROVALS_EN        float64
DISAPPROVALS_FM        float64
DISAPPROVALS_OM        float64
NOTE_BL                float64
NOTE_EN                float64
NOTE_FM                float64
NOTE_OM                float64
ENGLISH                float64
H_CLASS_PRES           float64
ONLINE_TASKS           float64
ABSENCES               float64
NOTE_BL_CAT             object
NOTE_EN_CAT             object
NOTE_FM_CAT             object
NOTE_OM_CAT             object
PROFILE_N              float64
DISAPPROVALS_HUMAN       int64
DISAPPROVALS_EXACTS      int64
NOTE_BL_CAT_N            int64
NOTE_EN_CAT_N            int64
NOTE_FM_CAT_N            int64
NOTE_OM_CAT_N            int64
dtype: object

In [10]:
# Arranging dataframe columns
a = ['DISAPPROVALS_BL', 'DISAPPROVALS_EN', 'DISAPPROVALS_HUMAN', 'DISAPPROVALS_FM','DISAPPROVALS_OM', 
     'DISAPPROVALS_EXACTS', 'NOTE_BL', 'NOTE_EN', 'NOTE_FM', 'NOTE_OM', 'NOTE_BL_CAT', 'NOTE_EN_CAT',
     'NOTE_FM_CAT', 'NOTE_OM_CAT', 'NOTE_BL_CAT_N', 'NOTE_EN_CAT_N', 'NOTE_FM_CAT_N', 'NOTE_OM_CAT_N', 
     'ENGLISH', 'H_CLASS_PRES', 'ONLINE_TASKS', 'ABSENCES', 'PROFILE_N']
df = df.reindex(columns= a)

In [11]:
df.shape

(18545, 23)

In [12]:
df.isna().sum()

DISAPPROVALS_BL        0
DISAPPROVALS_EN        0
DISAPPROVALS_HUMAN     0
DISAPPROVALS_FM        0
DISAPPROVALS_OM        0
DISAPPROVALS_EXACTS    0
NOTE_BL                0
NOTE_EN                0
NOTE_FM                0
NOTE_OM                0
NOTE_BL_CAT            0
NOTE_EN_CAT            0
NOTE_FM_CAT            0
NOTE_OM_CAT            0
NOTE_BL_CAT_N          0
NOTE_EN_CAT_N          0
NOTE_FM_CAT_N          0
NOTE_OM_CAT_N          0
ENGLISH                0
H_CLASS_PRES           0
ONLINE_TASKS           0
ABSENCES               0
PROFILE_N              0
dtype: int64

In [13]:
# Saving data
df.to_csv("Data/data3.csv", index= False)

In [14]:
# creating new dataframe and removing from categorical variables 
df1 = df.drop(['NOTE_BL_CAT', 'NOTE_EN_CAT', 'NOTE_FM_CAT', 'NOTE_OM_CAT'], axis= 1)
df1

,DISAPPROVALS_BL,DISAPPROVALS_EN,DISAPPROVALS_HUMAN,DISAPPROVALS_FM,DISAPPROVALS_OM,DISAPPROVALS_EXACTS,NOTE_BL,NOTE_EN,NOTE_FM,NOTE_OM,NOTE_BL_CAT_N,NOTE_EN_CAT_N,NOTE_FM_CAT_N,NOTE_OM_CAT_N,ENGLISH,H_CLASS_PRES,ONLINE_TASKS,ABSENCES,PROFILE_N
0,0.0,0.0,0,0.0,0.0,0,6.2,5.8,4.6,5.9,8,6,6,6,0.0,2.0,4.0,3.0,2.0
1,0.0,0.0,0,0.0,0.0,0,6.0,6.2,5.2,4.5,6,8,6,6,1.0,2.0,4.0,3.0,2.0
2,0.0,0.0,0,0.0,0.0,0,7.3,6.7,7.1,7.2,8,8,8,8,0.0,5.0,0.0,3.0,3.0
3,1.0,3.0,1,1.0,1.0,1,0.0,0.0,0.0,0.0,2,2,2,2,1.0,4.0,4.0,4.0,1.0
4,1.0,3.0,1,1.0,1.0,1,0.0,0.0,0.0,0.0,2,2,2,2,1.0,5.0,2.0,5.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18540,1.0,1.0,1,1.0,1.0,1,0.0,0.0,0.0,0.0,2,2,2,2,1.0,20.0,4.0,4.0,1.0
18541,0.0,0.0,0,0.0,0.0,0,7.0,7.9,5.8,7.0,8,8,6,8,1.0,9.0,5.0,6.0,2.0
18542,0.0,0.0,0,0.0,0.0,0,7.9,7.6,8.3,7.2,8,8,10,8,1.0,8.0,3.0,1.0,5.0
18543,0.0,0.0,0,1.0,1.0,1,6.3,5.1,0.0,0.0,8,6,2,2,1.0,3.0,2.0,6.0,1.0
18544,0.0,0.0,0,1.0,1.0,1,7.0,7.3,0.0,0.0,8,8,2,2,1.0,3.0,0.0,6.0,1.0

In [15]:
df1.shape

(18545, 19)

In [16]:
# Checking data type
df1.dtypes

DISAPPROVALS_BL        float64
DISAPPROVALS_EN        float64
DISAPPROVALS_HUMAN       int64
DISAPPROVALS_FM        float64
DISAPPROVALS_OM        float64
DISAPPROVALS_EXACTS      int64
NOTE_BL                float64
NOTE_EN                float64
NOTE_FM                float64
NOTE_OM                float64
NOTE_BL_CAT_N            int64
NOTE_EN_CAT_N            int64
NOTE_FM_CAT_N            int64
NOTE_OM_CAT_N            int64
ENGLISH                float64
H_CLASS_PRES           float64
ONLINE_TASKS           float64
ABSENCES               float64
PROFILE_N              float64
dtype: object

In [17]:
df1.isna().sum()

DISAPPROVALS_BL        0
DISAPPROVALS_EN        0
DISAPPROVALS_HUMAN     0
DISAPPROVALS_FM        0
DISAPPROVALS_OM        0
DISAPPROVALS_EXACTS    0
NOTE_BL                0
NOTE_EN                0
NOTE_FM                0
NOTE_OM                0
NOTE_BL_CAT_N          0
NOTE_EN_CAT_N          0
NOTE_FM_CAT_N          0
NOTE_OM_CAT_N          0
ENGLISH                0
H_CLASS_PRES           0
ONLINE_TASKS           0
ABSENCES               0
PROFILE_N              0
dtype: int64

<font color="blue">Applying feature selection</font>

In [18]:
x = df1.iloc[:, 0:18]
y = df1.PROFILE_N

In [19]:
x.shape

(18545, 18)

In [20]:
y.shape

(18545,)

In [26]:
feature_selection = pd.DataFrame(SelectKBest(chi2, k= 10).fit_transform(x, y))
feature_selection["TARGET"]= y
feature_selection.head(15)

      0    1    2    3    4    5    6    7    8    9  TARGET
0   0.0  0.0  0.0  0.0  0.0  6.2  5.8  4.6  6.0  2.0     2.0
1   0.0  0.0  0.0  0.0  0.0  6.0  6.2  5.2  6.0  2.0     2.0
2   0.0  0.0  0.0  0.0  0.0  7.3  6.7  7.1  8.0  5.0     3.0
3   1.0  3.0  1.0  1.0  1.0  0.0  0.0  0.0  2.0  4.0     1.0
4   1.0  3.0  1.0  1.0  1.0  0.0  0.0  0.0  2.0  5.0     1.0
5   0.0  0.0  0.0  0.0  0.0  7.3  7.4  7.6  8.0  5.0     3.0
6   0.0  0.0  0.0  0.0  0.0  5.8  6.0  7.3  8.0  5.0     1.0
7   0.0  0.0  0.0  0.0  0.0  4.9  5.0  5.9  6.0  2.0     1.0
8   0.0  0.0  0.0  0.0  0.0  4.4  4.8  4.7  6.0  3.0     1.0
9   0.0  0.0  0.0  0.0  0.0  6.4  5.4  5.0  6.0  3.0     2.0
10  0.0  0.0  0.0  0.0  0.0  6.9  7.5  7.3  8.0  3.0     4.0
11  3.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  2.0  0.0     1.0
12  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  2.0  7.0     1.0
13  3.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  2.0  6.0     1.0
14  1.0  3.0  1.0  1.0  1.0  0.0  0.0  0.0  2.0  5.0     1.0

In [31]:
# saving feature selection in csv format
feature_selection.to_csv("Data/selection_variables.csv", index= False)